# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
# default_velocity_scaling_factor: 0.1
# default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  joint1:
    has_position_limits: true
    min_position: -3.14159265359
    max_position: 3.14159265359
    has_velocity_limits: true
    max_velocity: 3.078760800518
    has_acceleration_limits: true
    max_acceleration: 4.68483115009004
  joint2:
    has_position_limits: true
    min_position: -1.83259571459
    max_position: 2.44346095279
    has_velocity_limits: true
    max_velocity: 3.078760800518
    has_acceleration_limits: true
    max_acceleration: 4.84328867428427
  joint3:
    has_position_limits: true
    min_position: -2.70526034059
    max_position: 2.35619449019
    has_velocity_limits: true
    max_velocity: 3.16428193386572
    has_acceleration_limits: true
    max_acceleration: 4.97469573133849
  joint4:
    has_position_limits: true
    min_position: -6.28318530718
    max_position: 6.28318530718
    has_velocity_limits: true
    max_velocity: 4.44709893408155
    has_acceleration_limits: true
    max_acceleration: 9.76690872804774
  joint5:
    has_position_limits: true
    min_position: -2.53072741539
    max_position: 2.53072741539
    has_velocity_limits: true
    max_velocity: 4.44709893408155
    has_acceleration_limits: true
    max_acceleration: 12.6051557088479
  joint6:
    has_position_limits: true
    min_position: -6.28318530718
    max_position: 6.28318530718
    has_velocity_limits: true
    max_velocity: 6.15752160103599
    has_acceleration_limits: true
    max_acceleration: 19.6602895095619